Add username/domain to url for each creator
dappforce/subid pull request #126
Opened 2023-12-18 14:15 UTC by samchuk-vlad

2023-12-18 16:28 UTC, olehmell requested changes

2023-12-18 16:28 UTC, olehmell commented on src/components/chat/ChatIframe.tsx
> +  console.log(isCreatorStaking, window.location.href)
remove

2023-12-18 16:28 UTC, olehmell commented on src/components/creatorsStaking/Creators/CreatorCard.tsx
> +                `/creators/${domainName ? '@' + domainName : spaceId}`,
do a function for building the string I guess

2023-12-18 16:28 UTC, olehmell commented on src/components/creatorsStaking/Creators/modals/AboutModal.tsx
> +          )
I guess it isnt first replace implementation (you are doing similar stuff for x-transfers), so maybe will be good create wrappers for managing parameters (I guess just create a task into backlog)

2023-12-18 16:28 UTC, olehmell commented on src/components/creatorsStaking/Creators/modals/DefaultAboutModal.tsx
> +      if (query.creator) {
why not just `if (router.query.creator)`?

2023-12-18 16:28 UTC, olehmell commented on src/components/creatorsStaking/Creators/modals/MoveStakeModal.tsx
> +          router.replace('/creators', '/creators', { scroll: false })
Same code in DefaultAboutModal

2023-12-18 16:28 UTC, olehmell commented on src/components/creatorsStaking/Creators/modals/StakeModal.tsx
> +          router.replace('/creators', '/creators', { scroll: false })
Same code in DefaultAboutModal and MoveStakeModal

2023-12-18 16:28 UTC, olehmell commented on src/pages/creators/[creator].tsx
> +      image: '/images/creator-staking/meta-bg.jpg',
```suggestion
      // TODO: create auto-generated image for particular creator, we can use this one: https://nextjs.org/docs/app/api-reference/functions/image-response
      image: '/images/creator-staking/meta-bg.jpg',
```

2023-12-18 16:28 UTC, olehmell commented on src/pages/creators/index.tsx
> +    spaceId: '',
Why not skip the parameters?

2023-12-19 12:20 UTC, samchuk-vlad commented on src/pages/creators/index.tsx
> +    spaceId: '',
We use same component for both pages and I need to provide this parameter because of the type of this CreatorStakingPage component

2023-12-19 12:31 UTC, olehmell approved these changes

2023-12-19 12:31 UTC, merged