Add tx history tab
dappforce/subid pull request #135
Opened 2024-01-11 13:46 UTC by samchuk-vlad

2024-01-11 16:44 UTC, teodorus-nathaniel requested changes

2024-01-11 16:44 UTC, teodorus-nathaniel commented on src/components/accountDashboard/index.tsx
> +  useGetTableData(currentAddresses, 'chains')
the return value is not used, is it intentional?

2024-01-11 16:44 UTC, teodorus-nathaniel commented on src/components/txHistory/useGetTxHistory.tsx
> +    intervalRef.current = setInterval(async () => {
instead of using ref, you can just save the interval in a variable inside of useEffect, like what you did in 
src/components/txHistory/index.tsx (bottom part)

2024-01-11 16:44 UTC, teodorus-nathaniel commented on src/components/utils/Dropdowns/SelectbleDropdown.tsx
> +type SelectbleMenuItem = MenuItem & {
typo

2024-01-16 16:47 UTC, olehmell approved these changes

2024-01-16 16:47 UTC, merged